/* SCRIPT DE ESTRUCTURA */

CREATE SCHEMA digitalwine;

USE digitalwine;

CREATE TABLE users (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    last_name VARCHAR (50) NOT NULL,
    email VARCHAR (50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    dob DATETIME NOT NULL,
    avatar VARCHAR(255),
	rol INT NOT NULL DEFAULT 10,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- FECHA DE ALTA
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP, -- FECHA DE MODIFICACION
    deleted_at DATETIME -- FECHA DE BORRADO DEL REGISTRO COMPLETO	
);

CREATE TABLE products (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    price DECIMAL UNSIGNED NOT NULL,
    detail TEXT NOT NULL,
    discount INT UNSIGNED DEFAULT 0,
    varietal VARCHAR(30),
    wine_cellar VARCHAR(100),
    image VARCHAR(255) NOT NULL,
    category_id INT UNSIGNED,

	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- FECHA DE ALTA
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP, -- FECHA DE MODIFICACION
    deleted_at DATETIME -- FECHA DE BORRADO DEL REGISTRO COMPLETO	
);

CREATE TABLE categories (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- FECHA DE ALTA
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP, -- FECHA DE MODIFICACION
    deleted_at DATETIME -- FECHA DE BORRADO DEL REGISTRO COMPLETO	
);

CREATE TABLE user_products (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    
    product_id INT UNSIGNED,
    user_id INT UNSIGNED,
    
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- FECHA DE ALTA
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP, -- FECHA DE MODIFICACION
    deleted_at DATETIME -- FECHA DE BORRADO DEL REGISTRO COMPLETO	
);

ALTER TABLE user_products 
	ADD FOREIGN KEY (product_id) REFERENCES products(id),
	ADD FOREIGN KEY (user_id) REFERENCES users(id);
	
ALTER TABLE products
	ADD FOREIGN KEY (category_id) REFERENCES categories(id);
